[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vivamir"
version = "1.0.1"
description = 'AMD Vivado mirroring utility'
readme = "README.md"
requires-python = ">=3.6"
license = { file = "LICENSE" }
keywords = []
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.6",
]
dependencies = [
    "rich",
    "typer",
    "dacite"
]

[project.scripts]
vivamir = "vivamir.main:main"
